Update README.md
ligurio/awesome-openbsd pull request #29
Opened 2022-05-09 14:41 UTC by nerfur

removed dead link to telegram chat
add 3 more (global english, russian, chinese) telegram chats

2022-05-09 15:34 UTC, ligurio requested changes
Please update a patch

2022-05-09 15:34 UTC, ligurio commented on README.md
> -* `telegram` [OpenBSD Jumpstart](https://t.me/joinchat/EzTjLQuG8Mcj89LYcDGKiQ)
Valid link is https://t.me/joinchat/EzTjLQuG8MdUSVqFS1xA4w

2022-05-09 20:52 UTC, ligurio requested changes

2022-05-09 20:52 UTC, ligurio commented on README.md
> +* `telegram` [OpenBSD 中文结社 🐡](https://t.me/openbsd_zh)
I would remove emodji and replace "中文结社" with "chinese" or "China" to make it consistent with other items.

2022-05-09 20:52 UTC, ligurio commented on README.md
> +* `telegram` [OpenBSD (russian)](https://t.me/openbsd_ru)
Round brackets can be removed

2022-05-09 21:37 UTC, nerfur reviewed
ok, btw, why not join our russian-language tg ? :D

2022-05-11 09:37 UTC, ligurio requested changes

2022-05-11 09:37 UTC, ligurio commented on README.md
> +* `telegram` [OpenBSD](https://t.me/openbsd_en)
Shouldn't we specify here language too?

2022-05-13 19:26 UTC, ligurio commented on README.md
> +* `telegram` [OpenBSD](https://t.me/openbsd_en)
Fixed.

```diff
--- a/README.md
+++ b/README.md
@@ -174,10 +174,10 @@
 * `irc` [#OpenBSD](https://web.libera.chat/?channels=#openbsd) on irc.libera.chat
 * `irc` [#OpenBSD-Russian](http://webchat.freenode.net?channels=%23openbsd-russian) on irc.freenode.net
 * `matrix` [OpenBSD](https://matrix.to/#/%23openbsd%3Amatrix.org)
-* `telegram` [OpenBSD](https://t.me/openbsd_en)
 * `telegram` [OpenBSD Jumpstart](https://t.me/joinchat/EzTjLQuG8MdUSVqFS1xA4w)
-* `telegram` [OpenBSD russian](https://t.me/openbsd_ru)
-* `telegram` [OpenBSD chinese](https://t.me/openbsd_zh)
+* `telegram` [OpenBSD English](https://t.me/openbsd_en)
+* `telegram` [OpenBSD Russian](https://t.me/openbsd_ru)
+* `telegram` [OpenBSD Chinese](https://t.me/openbsd_zh)
 * `telegram` [OpenBSD Brazil](https://t.me/OpenBSDbr)
 * `telegram` [OpenBSD Spain](https://t.me/OpenBSD_es)
 * `telegram` [BSDar Argentina](https://t.me/BSDar)
```

2022-05-13 19:31 UTC, merged